language: python

env:
    global:
        - PACKAGE="PHPGrammar"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

services:
  - xvfb

matrix:
    fast_finish: true
    include:
        - os: linux
          python: 3.3
        - os: linux
          python: 3.6
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                pip install flake8==3.5;
                pip install pydocstyle==3.0.0
                pip install flake8-docstrings;
                pip install python-coveralls;
            else
                pip install flake8;
                pip install pydocstyle==3.0.0
                pip install flake8-docstrings;
                pip install python-coveralls;
            fi
      fi
    - sh travis.sh bootstrap
    - python --version

script:
    - sh travis.sh run_tests --coverage
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            flake8 --version;
            flake8;
      fi

after_success:
    - coveralls

notifications:
    email: false
