language: python

env:
    global:
        - PACKAGE="PHPGrammar"
    matrix:
        - SUBLIME_TEXT_VERSION="3"

matrix:
    fast_finish: true
    include:
        - os: linux
          python: 3.3
        - os: linux
          python: 3.6
        - os: osx
          language: generic

before_install:
    - curl -OL https://raw.githubusercontent.com/SublimeText/UnitTesting/master/sbin/travis.sh
    # Enable GUI. See https://docs.travis-ci.com/user/gui-and-headless-browsers.
    - if [ "$TRAVIS_OS_NAME" == "linux"  ]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
      fi

install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            if [ "$TRAVIS_PYTHON_VERSION" == "3.3" ]; then
                pip install flake8==3.5;
                pip install flake8-docstrings;
                pip install python-coveralls;
            else
                pip install flake8;
                pip install flake8-docstrings;
                pip install python-coveralls;
            fi
      fi
    - sh travis.sh bootstrap
    - python --version

script:
    - sh travis.sh run_tests --coverage
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
            flake8 --version;
            flake8;
      fi

after_success:
    - coveralls

notifications:
    email: false
